# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"|\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x18\n\x10transaction_date\x18\x05 \x01(\t\x12\x16\n\x0epayment_method\x18\x06 \x01(\t\"/\n\x07Product\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"v\n\x05Order\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\"\n\x08products\x18\x02 \x03(\x0b\x32\x10.payment.Product\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x02\x12\x12\n\norder_date\x18\x05 \x01(\t\"\x80\x01\n\x07Payment\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"5\n\x10PaymentProcessed\x12!\n\x07payment\x18\x01 \x01(\x0b\x32\x10.payment.Payment\"4\n\x0fPaymentRefunded\x12!\n\x07payment\x18\x01 \x01(\x0b\x32\x10.payment.Paymentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=26
  _globals['_TRANSACTION']._serialized_end=150
  _globals['_PRODUCT']._serialized_start=152
  _globals['_PRODUCT']._serialized_end=199
  _globals['_ORDER']._serialized_start=201
  _globals['_ORDER']._serialized_end=319
  _globals['_PAYMENT']._serialized_start=322
  _globals['_PAYMENT']._serialized_end=450
  _globals['_PAYMENTPROCESSED']._serialized_start=452
  _globals['_PAYMENTPROCESSED']._serialized_end=505
  _globals['_PAYMENTREFUNDED']._serialized_start=507
  _globals['_PAYMENTREFUNDED']._serialized_end=559
# @@protoc_insertion_point(module_scope)
